#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(git -C "$SCRIPT_DIR/../.." rev-parse --show-toplevel)"
cd "$ROOT"

echo "Public artifact validation"
echo "Repository: $ROOT"

python3 - <<'PYV'
from __future__ import annotations

import pathlib
import re
import subprocess
import sys

repo = pathlib.Path.cwd()
result = subprocess.run(
    ["git", "ls-files", "-co", "--exclude-standard", "-z"],
    check=True,
    stdout=subprocess.PIPE,
)
paths = [
    pathlib.Path(item.decode("utf-8", errors="surrogateescape"))
    for item in result.stdout.split(b"\0") if item
]

forbidden_suffixes = {
    ".pcap", ".pcapng", ".cap", ".keylog", ".keys", ".har",
    ".apk", ".apks", ".aab", ".so", ".hci", ".pyc",
    ".img", ".bin", ".mbn", ".elf", ".dump", ".dmp",
}

# These patterns identify raw/private evidence artifacts. They must not reject
# source code, safety tooling, or documentation whose *purpose* is to verify or
# describe private-evidence handling. For example,
# scripts/safety/verify_private_evidence_manifest.sh is legitimate tooling.
raw_artifact_name_patterns = [
    re.compile(r"bugreport.*\.zip$", re.I),
    re.compile(r"private[-_ ]?evidence", re.I),
    re.compile(r"private-raw-do-not-upload", re.I),
    re.compile(r"sanitized-upload.*\.zip$", re.I),
    re.compile(r"sslkeylog", re.I),
    re.compile(r"selected[-_ ]?apks", re.I),
    re.compile(r"(?:boot|vbmeta|vendor|super|recovery)[-_ ]?partition", re.I),
]
name_scan_exempt_suffixes = {".sh", ".py", ".md"}

sensitive_patterns = [
    re.compile(r"/Users/[A-Za-z0-9._-]+"),
    re.compile(r"C:\\Users\\[A-Za-z0-9._-]+", re.I),
    re.compile(r"\bR5C[A-Z0-9]{8,}\b"),
    re.compile(r"\bBearer\s+[A-Za-z0-9._~-]{12,}", re.I),
    re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b"),
    re.compile(r"\b(?:[0-9A-F]{2}:){5}[0-9A-F]{2}\b", re.I),
    re.compile(r'(?i)(latitude|longitude|"(?:lat|lon|lng)")\s*[:=]\s*-?\d{1,3}\.\d{4,}'),
]

errors: list[str] = []
for relative in paths:
    path = repo / relative
    if not path.is_file():
        continue

    relative_posix = relative.as_posix()
    lowered_path = relative_posix.lower()
    suffix = path.suffix.lower()
    if "__pycache__" in relative.parts:
        errors.append(f"prohibited generated bytecode cache: {relative}")
        continue
    is_hash_manifest = (
        relative.parts[:2] == ("evidence", "manifests")
        and suffix == ".json"
    )
    is_name_scan_exempt = suffix in name_scan_exempt_suffixes

    if suffix in forbidden_suffixes:
        errors.append(f"prohibited raw/private artifact: {relative}")
        continue

    if (
        not is_hash_manifest
        and not is_name_scan_exempt
        and any(pattern.search(lowered_path) for pattern in raw_artifact_name_patterns)
    ):
        errors.append(f"prohibited raw/private artifact: {relative}")
        continue

    # The validator necessarily contains the patterns it enforces.
    if relative_posix == "scripts/safety/validate_public_repo.sh":
        continue

    try:
        text = path.read_text(encoding="utf-8")
    except (UnicodeDecodeError, OSError):
        continue

    for pattern in sensitive_patterns:
        match = pattern.search(text)
        if match:
            line = text.count("\n", 0, match.start()) + 1
            errors.append(f"sensitive value/path pattern: {relative}:{line}")
            break

if errors:
    print("ERROR: public artifact validation failed:", file=sys.stderr)
    for error in errors:
        print(f"  {error}", file=sys.stderr)
    raise SystemExit(1)
PYV

PYCACHE_DIR="$(mktemp -d)"
trap 'rm -rf "$PYCACHE_DIR"' EXIT
PYTHONPYCACHEPREFIX="$PYCACHE_DIR" \
  python3 -m py_compile scripts/tests/*.py scripts/recovery/*.py

for script in scripts/tests/*.sh scripts/safety/*.sh; do
  [[ -f "$script" ]] || continue
  bash -n "$script"
done

python3 - <<'PYJSON'
from __future__ import annotations
import json
import pathlib

for path in pathlib.Path("evidence").rglob("*.json"):
    json.loads(path.read_text(encoding="utf-8"))
PYJSON

git diff --check

echo "Public artifact validation: PASS"
